# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e590d65b79b59c27171bb12c1ea4a5ec57f8a828f27e7ac8a02eceb283ebababa347ad7b3d850e10faa2569cf494cf1e79179e911b324c4ee4da3f8ee2b73362

test:
  secret_key_base: d9f0a5193ac02894b09924060e746df725ac8ef89e094acec627bf628498f7d1adf73747f4a92cf9e1480fa125c947b126be250703cdea66b9edfe212309f7b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
